# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
array_1 = np.array([1, 2, 3])

# Create a 2-dimensional NumPy array using np.array()
array_2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Create a 3-dimensional Numpy array using np.array()
array_3 = np.array([[[1, 2], [2, 3]], [[4, 5], [6, 7]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
print(array_1.shape)
print(array_1.ndim)
print(array_1.dtype)
print(array_1.size)
print(type(array_1))


(3,)
1
int64
3
<class 'numpy.ndarray'>


In [4]:
# Attributes of 2-dimensional array
print(array_2.shape)
print(array_2.ndim)
print(array_2.dtype)
print(array_2.size)
print(type(array_2))

(3, 3)
2
int64
9
<class 'numpy.ndarray'>


In [5]:
# Attributes of 3-dimensional array
print(array_3.shape)
print(array_3.ndim)
print(array_3.dtype)
print(array_3.size)
print(type(array_3))

(2, 2, 2)
3
int64
8
<class 'numpy.ndarray'>


In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df = pd.DataFrame(array_2)
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [7]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7, 2, 3))

In [9]:
# Create an array within a range of 0 and 100 with step 3
rg = np.array(range(0, 100, 3))
rg

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [10]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
rndm = np.random.randint(10, size = (7, 2))
rndm

array([[8, 5],
       [5, 1],
       [0, 5],
       [6, 0],
       [3, 9],
       [7, 2],
       [3, 7]])

In [11]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
rndm_2 = np.random.random((7, 2))
rndm_2

array([[0.24972671, 0.92995605],
       [0.15548421, 0.16078281],
       [0.94421369, 0.76774385],
       [0.1300497 , 0.47470397],
       [0.55676933, 0.22539742],
       [0.52346827, 0.45296584],
       [0.84303153, 0.1273299 ]])

In [12]:
# Set the random seed to 42
seed = np.random.seed(2)

# Create a random array of numbers between 0 & 10 of size (4, 6)
array = np.random.randint(10, size = (4, 6))
array

array([[8, 8, 6, 2, 8, 7],
       [2, 1, 5, 4, 4, 5],
       [7, 3, 6, 4, 3, 7],
       [6, 1, 3, 5, 8, 4]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [13]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
array_rand = np.random.randint(10, size = (3, 7))
array_rand
# Find the unique numbers in the array you just created


array([[6, 3, 9, 2, 0, 4, 2],
       [4, 1, 7, 8, 2, 9, 8],
       [7, 1, 6, 8, 5, 9, 9]])

In [14]:
# Find the 0'th index of the latest array you created
array_rand[0, 0]

6

In [15]:
# Get the first 2 rows of latest array you created
array_rand[0:2]

array([[6, 3, 9, 2, 0, 4, 2],
       [4, 1, 7, 8, 2, 9, 8]])

In [16]:
# Get the first 2 values of the first 2 rows of the latest array
array_rand[0:2, 0]

array([6, 4])

In [17]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
rand_array = np.random.randint(10, size = (3, 5))
ones = np.ones((3, 5), dtype=int)
rand_array

array([[9, 3, 0, 0, 2],
       [8, 8, 2, 9, 6],
       [5, 6, 6, 6, 3]])

In [18]:
# Add the two arrays together
rand_array + ones

array([[10,  4,  1,  1,  3],
       [ 9,  9,  3, 10,  7],
       [ 6,  7,  7,  7,  4]])

In [19]:
# Create another array of ones of shape (5, 3)
ones_2 = np.ones((5, 3), dtype = int)

In [20]:
# Try add the array of ones and the other most recent array together
rand_array + ones_2

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [21]:
# Create another array of ones of shape (3, 5)
ones_3 = np.ones((3, 5), dtype = int)

In [22]:
# Subtract the new array of ones from the other most recent array
rand_array - ones_3

array([[ 8,  2, -1, -1,  1],
       [ 7,  7,  1,  8,  5],
       [ 4,  5,  5,  5,  2]])

In [23]:
# Multiply the ones array with the latest array
rand_array * ones_3

array([[9, 3, 0, 0, 2],
       [8, 8, 2, 9, 6],
       [5, 6, 6, 6, 3]])

In [24]:
# Take the latest array to the power of 2 using '**'
rand_array ** 2

array([[81,  9,  0,  0,  4],
       [64, 64,  4, 81, 36],
       [25, 36, 36, 36,  9]])

In [25]:
# Do the same thing with np.square()
np.square(rand_array)

array([[81,  9,  0,  0,  4],
       [64, 64,  4, 81, 36],
       [25, 36, 36, 36,  9]])

In [26]:
# Find the mean of the latest array using np.mean()
np.mean(rand_array)

4.866666666666666

In [27]:
# Find the maximum of the latest array using np.max()
np.max(rand_array)

9

In [51]:
# Find the minimum of the latest array using np.min()
np.min(rand_array)

0

In [56]:
# Find the standard deviation of the latest array
np.std(rand_array)

2.94089933334837

In [54]:
# Find the variance of the latest array
np.var(rand_array)

8.648888888888887

In [57]:
# Reshape the latest array to (3, 5, 1)
np.reshape(rand_array, newshape = (3, 5, 1))
rand_array

array([[9, 3, 0, 0, 2],
       [8, 8, 2, 9, 6],
       [5, 6, 6, 6, 3]])

In [58]:
# Transpose the latest array
rand_array.T

array([[9, 8, 5],
       [3, 8, 6],
       [0, 2, 6],
       [0, 9, 6],
       [2, 6, 3]])

What does the transpose do?

In [60]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
rand_array_1 = np.random.randint(1, 10, size = (3, 3))
rand_array_2 = np.random.randint(1, 10, size = (3, 2))

In [61]:
# Perform a dot product on the two newest arrays you created
np.dot(rand_array_1, rand_array_2)

array([[76, 90],
       [59, 86],
       [89, 80]])

In [63]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
rand_array3 = np.random.randint(1, 10, size = (4, 3))
rand_array4 = np.random.randint(1, 10, size = (4, 3))

In [64]:
# Perform a dot product on the two newest arrays you created
np.dot(rand_array3, rand_array4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [65]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(rand_array3, rand_array4.T)

array([[ 38,  83,  72,  56],
       [110,  88,  70,  48],
       [ 43,  67,  57,  47],
       [ 64,  68,  56,  36]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [67]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
ra
print(rand_array4)

[[1 8 2]
 [9 1 8]
 [1 6 3]
 [6 2 4]]
[[4 2 9]
 [7 9 2]
 [6 8 1]
 [2 6 3]]


In [68]:
# Compare the two arrays with '>'
rand_array3 > rand_array4

array([[False,  True, False],
       [ True, False,  True],
       [False, False,  True],
       [ True, False,  True]])

What happens when you compare the arrays with `>`?

In [69]:
# Compare the two arrays with '>='
rand_array3 >= rand_array4

array([[False,  True, False],
       [ True, False,  True],
       [False, False,  True],
       [ True, False,  True]])

In [70]:
# Find which elements of the first array are greater than 7
rand_array3 > 7

array([[False,  True, False],
       [ True, False,  True],
       [False, False, False],
       [False, False, False]])

In [71]:
# Which parts of each array are equal? (try using '==')
rand_array3 == rand_array4

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [72]:
# Sort one of the arrays you just created in ascending order
np.sort(rand_array3)

array([[1, 2, 8],
       [1, 8, 9],
       [1, 3, 6],
       [2, 4, 6]])

In [76]:
# Sort the indexes of one of the arrays you just created
np.argsort(rand_array3)

array([[0, 2, 1],
       [1, 2, 0],
       [0, 2, 1],
       [1, 2, 0]])

In [84]:
# Find the index with the maximum value in one of the arrays you've created
np.where(rand_array3 == rand_array3.max())

(array([1]), array([0]))

In [85]:
# Find the index with the minimum value in one of the arrays you've created
np.where(rand_array3 == rand_array3.min())


(array([0, 1, 2]), array([0, 1, 0]))

In [86]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(rand_array3, axis = 1)

array([1, 0, 1, 0])

In [87]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(rand_array3, axis = 1)

array([0, 1, 0, 1])

In [88]:
# Create an array of normally distributed random numbers
np.random.normal(loc = 0, scale = 1, size = (3, 3))

array([[ 0.42497798,  1.12208984,  0.34265413],
       [-1.21388478,  2.97314956, -0.66614005],
       [-1.03942856,  0.81587939, -0.02716851]])

In [95]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(start = 0, stop = 100, num = 5)

array([  0.,  25.,  50.,  75., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.